# Generated by Django 3.2.8 on 2021-10-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.TextField(max_length=200)),
                ('nama', models.CharField(max_length=200)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='minuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.TextField(max_length=200)),
                ('nama', models.CharField(max_length=200)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_makanan', models.TextField(max_length=200)),
                ('jumlah_pesanan_makanan', models.IntegerField()),
                ('nama_minuman', models.CharField(max_length=200)),
                ('jumlah_pesanan_minuman', models.IntegerField()),
            ],
        ),
    ]
